### ISSUE TITLE
Feature request: Image file name formatting.

### ISSUE THREAD

**Issue by darylrobert** [castholm/twimgdump#1]
for example:
`[username]_[TweetID]_[imagenumber]-[totalimagecount]_[serverformat]_[serversize]_[serverfilename]_IMG_[ISO8601date]_[ISO8601time].extension`

**Comment by castholm** [comment]
I've added tentative support for this as of f767ae8 by changing the `--output` option to take a file path template.

The following tokens can be substituted (case-insensitive):
* `[userId]` (the internal user ID, not usually exposed)
* `[username]`
* `[tweetId]`
* `[created]` (the tweet timestamp, formatted as `yyyyMMddHHmmss`, e.g. `20200412061453`)
* `[count]` (the number of media included in the tweet)
* `[mediaId]` (the internal media ID, not usually exposed)
* `[index]` (the 1-based index of the media)
* `[baseName]` (the original filename without the file extension, e.g. `EVYecHaUUAIVjZt`)
* `[extension]` (e.g. `jpg` (does not include the dot))
* `[width]`
* `[height]`

I might change and move these around. In particular I think I might split `[created]` up into more granular alternatives like `[year]`, `[month]`, etc. to make it possible to group media into directories based on date. Let me know if you have any other suggestions.

Note that the tool does not currently warn you if you specify parameters that would result in the file path being non-unique and downloaded media overriding one another, so take care to always include `[tweetId]` + `[index]`, `[mediaId]` or `[baseName]` if you want to avoid that.

**Comment by castholm** [comment]
As of 15835e1, I've settled on the following tokens:

* `[user-id]` (the internal user ID, not usually exposed)
* `[username]`
* `[tweet-id]`
* `[year]`, `[month]`, `[day]`, `[hour]`, `[minute]`, `[second]`, `[millisecond]` (the tweet timestamp, adjusted to UTC)
* `[media-id]` (the internal media ID, not usually exposed)
* `[stem]` (the original filename stem without the filename extension, e.g. `EVYecHaUUAIVjZt`)
* `[extension]` (e.g. `.jpg` (includes the dot))
* `[index]` (the 1-based index of the media)
* `[count]` (the number of media included in the tweet)
* `[width]`
* `[height]`
